name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
    env:
        BASE_URL: https://inenuitvoer.dev.sduoneplatform.nl/
        APP_USERNAME: titansdu@gmail.com
        PASSWORD: Gjk5lel@oa!ka4

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with tracing enabled
        run: npx playwright test --trace on

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Playwright trace files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/

      - name: Upload pre-login screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pre-login-screenshots
          path: |
            screenshot-before-inloggen.png
            screenshot-before-inloggen2.png
